export default {
  INIT_TODO : 'INIT_TODO',
  ADD_TODO_INPUT : 'ADD_TODO_INPUT',
  CHANGE_TODO_STATE: 'CHANGE_TODO_STATE',
  DESTROY_TODO: 'DESTROY_TODO',
  CHANGE_SHOW_STATE: 'CHANGE_SHOW_STATE',
  CLEAR_COMPLETED : 'CLEAR_COMPLETED',
}
